// Package EchoApp GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package EchoApp

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Endpoint básico que muestra mensaje de bienvenida en el servidor.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Muestra mensaje de bienvenida.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/hello_world": {
            "get": {
                "description": "Endpoint que muestra el HelloWorld de la variable ingresada.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HelloWorld"
                ],
                "summary": "hello world sencillo.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valor que se mostrará en la respuesta",
                        "name": "nombre",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/usopathparams/{value}": {
            "get": {
                "description": "Endpoint que muestra el valor de la variable especificada por path.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UsoParametros"
                ],
                "summary": "Muestra valor de variable especificada.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valor que se mostrará en la respuesta",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/usoqueryparams": {
            "get": {
                "description": "Endpoint que muestra el valor de la variable 'value' especificada por query.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UsoQuery"
                ],
                "summary": "Muestra valor de la variable value especificada.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valor que se mostrará en la respuesta",
                        "name": "value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3333",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "API ECHO de prueba",
	Description:      "Este es un ejemplo sencillo utilizando Echo para crear una api.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
